### ISSUE TITLE
Traditional Character Chinese translation completed and ready to be deployed

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/floatingforests#56]
They only thing noticed by the translators that might be due to the way it is temporarily deployed, is that if you click on the Favorites button once, the button then switches to english with the text 'Favorited' and then 'Add to Favorites' if you click it again

Looks like I see this behavior on the live Polish translation as well.

**Comment by mschwamb** [comment]
Any chance this could be deployed in the coming months? Thanks

**Comment by astopy** [comment]
This is deployed now.

**Comment by jebyrnes** [comment]
This is fantastic! Not showing up on the site yet, but will get the word out as soon as it does!

On May 16, 2016, at 6:25 AM, Adam McMaster <notifications@github.com<mailto:notifications@github.com>> wrote:


This is deployed now.

**Comment by eatyourgreens** [comment]
@jebyrnes should be showing up on the language menu now. See ba7733066a4a484b49944a5f21868b5af3b29e20
